name: mol2image
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - gunicorn
  - scipy
  - numpy
  - tqdm
  - tensorboardx
  - flask
  - scikit-learn
  - hyperopt
  - rdkit
  - cudatoolkit=11.0
  - torchvision==0.8.0
  - pytorch==1.7.0
  - gulpio
